---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "BlissFlixx"
keywords:    "blissflixx, media, streaming, raspberry pi"
description: "Turn your Raspberry Pi into a media stream"
source_link: "https://github.com/blissland/blissflixx"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-60078673-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:       '#111111'
  white:       '#ffffff'
  lightgreen:  '#99b433'
  green:       '#00a300'
  darkgreen:   '#1e7145'
  magenta:     '#ff0097'
  lightpurple: '#9f00a7'
  purple:      '#7e3878'
  darkpurple:  '#603cba'
  darken:      '#1d1d1d'
  teal:        '#00aba9'
  lightblue:   '#eff4ff'
  blue:        '#2d89ef'
  darkblue:    '#2b5797'
  yellow:      '#ffc40d'
  orange:      '#e3a21a'
  darkorange:  '#da532c'
  red:         '#ee1111'
  darkred:     '#b91d47'
